name: Build and Deploy to Azure Web App - mltestaz25

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: mltestaz25.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mltestaz25.azurecr.io/mltestimg:latest

      - name: Azure CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check resource group value
        run: echo "Using Resource Group: ${{ secrets.RESOURCE_GROUP }}"

      - name: Link ACR to Azure Web App using CLI
        run: |
          az webapp config container set \
            --name mltestaz25 \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --docker-custom-image-name mltestaz25.azurecr.io/mltestimg:latest \
            --docker-registry-server-url https://mltestaz25.azurecr.io \
            --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
            --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}

      - name: Restart Web App (optional but recommended)
        run: |
          az webapp restart \
            --name mltestaz25 \
            --resource-group ${{ secrets.RESOURCE_GROUP }}
